testingmode: false
graceful_timeout: "15s"
log.level: "info"
log.json: false
http.address: "0.0.0.0:8080"
http.insecure: true
http.cert_path: "server.rsa.crt"
http.key_path: "server.rsa.key"
http.compress: false
http.idle_timeout: "15s"
http.write_timeout: "15s"
http.read_timeout: "15s"
oid2.client_id: "oid_id"
oid2.client_secret: "oid_secret"
oid2.authorization_url: http://oid2-auth-server/